server:
  port: 18000
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: 1000000
  max-http-header-size: 1000000
spring:
  application:
    name: guiyu-cloud-zuul
  rabbitmq:
    host: 192.168.1.81
    port: 5672
    virtual-host: /
    username: guiyu
    password: 123456
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.5
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 100MB # 设置单个文件的最大长度
      max-request-size: 100MB # 设置最大的请求文件的大小
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /  # 上传的临时目录
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.57:3306/guiyu_base?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&allowMultiQueries=true
    username: base
    password: base@1234
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 5
    maxActive: 200
    initialSize: 5
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  redis:
    database: 0
    host: 192.168.1.81
    password: 123456
    port: 6379
    pool:
      max-active: 400
      max-wait: -1
      min-idle: 100
      max-idle: 300
  cache:
    type: redis
    cache-names: shiro.session,shiro.time
mybatis:
  mapperLocations: classpath*:mappers/*.xml
  config-location: classpath:config/mybatis-config.xml
properties:
  error: properties/error.properties
  whiteIP: properties/whiteIP.properties
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://guiyu-cloud-registeration:18001/eureka/
    instance:
      status-page-url: http://localhost:18000/swagger-ui.html
##网关地址
gateway:
  host: http://guiyu-cloud-zuul:18000/

###actuator监控点 start####
endpoints:
  health:
    sensitive: false
    enabled: true
##默认情况下很多端点是不允许访问的，会返回401:Unauthorized
management:
  security:
    enabled: false
###actuator监控点 end####

###如下Oauth2.0配置参考##
###https://stackoverflow.com/questions/30327269/spring-oauth-authorization-server-behind-spring-cloud-zuul-proxy##
###https://github.com/spring-guides/tut-spring-security-and-angular-js/blob/master/oauth2-vanilla/README.adoc##
###http://wiselyman.iteye.com/blog/2379419##
#######

zuul:
  routes:
    guiyu-auth-web:
      path: /auth/**
      service-id: guiyu-auth-web
    guiyu-dispatch-web:
      path: /dispatch/**
      service-id: guiyu-dispatch-web
    guiyu-nas-web:
      path: /nas/**
      service-id: guiyu-nas-web
    guiyu-cache:
      path: /cache/**
      service-id: guiyu-cache
    guiyu-datadic:
      path: /dict/**
      service-id: guiyu-datadic
    guiyu-ai-web:
      path: /ai/**
      service-id: guiyu-ai-web
    guiyu-robot-web:
      path: /robot/**
      service-id: guiyu-robot-web
    guiyu-callCenter-calloutserver:
      path: /callout/**
      service-id: guiyu-callCenter-calloutserver
    guiyu-callCenter-ccmanager:
      path: /ccmanager/**
      service-id: guiyu-callCenter-ccmanager
    guiyu-callCenter-fsagent:
      path: /fsagent/**
      service-id: guiyu-callCenter-fsagent
    guiyu-callCenter-fsline:
      path: /fsline/**
      service-id: guiyu-callCenter-fsline
    guiyu-callCenter-fsmanager:
      path: /fsmanager/**
      service-id: guiyu-callCenter-fsmanager
    guiyu-botstence-web:
      path: /botstence/**
      service-id: guiyu-botstence-web
    guiyu-process-web:
      path: /process/**
      service-id: guiyu-process-web
    guiyu-da-web:
      path: /da/**
      service-id: guiyu-da-web
    guiyu-sysoperalog-web:
      path: /log/**
      service-id: guiyu-sysoperalog-web
    guiyu-thirdApi-web:
      path: /api/**
      service-id: guiyu-thirdApi-web
    guiyu-thirdApi-web-api:
      path: /v1/**
      service-id: guiyu-thirdApi-web
    guiyu-callcenter-toagentserver:
      path: /toagent/**
      service-id: guiyu-callcenter-toagentserver
    guiyu-sms-web:
      path: /sms/**
      service-id: guiyu-sms-web
    guiyu-linemarket-web:
      path: /linemarket/**
      service-id: guiyu-linemarket-web
    guiyu-notice-web:
      path: /notice/**
      service-id: guiyu-notice-web
    guiyu-billing-web:
      path: /billing/**
      service-id: guiyu-billing-web
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false #禁用hystrix超时设置

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true
whiteIP: 127.0.0.1|192.168.1.81|192.168.1.50|172.16.167.213|172.16.167.214|172.16.167.215|192.168.1.57|192.168.1.161|172.16.168.93|192.168.1.173|192.168.1.124