server:
  port: 18031
  id: 1 #集群节点需要配置，新节点ID+1
spring:
  application:
    name: guiyu-dispatch-web
  # REDIS (RedisProperties)
  redis:
    database: 0
    host: 192.168.1.81
   # host: localhost
    password: 123456
    port: 6379  
    pool:
      max-active: 400 # 连接池最大连接数（使用负值表示没有限制
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 300 # 连接池中的最大空闲连接
      min-idle: 100 # 连接池中的最小空闲连接  
  cache:
    type: redis
    cache-names: shiro.session,shiro.time 
  rabbitmq:
    host: 192.168.1.81
    port: 5672
    virtual-host: /
    username: guiyu
    password: 123456
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.5

endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
#注册中心配置      
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
#      defaultZone: http://192.168.1.78:18001/eureka/
      defaultZone: http://guiyu-cloud-registeration:18001/eureka/
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  config-location: classpath:config/mybatis-config.xml
jdbc:
  type: mysql
ribbon:
  ReadTimeout: 30000 #请求处理的超时时间
  ConnectTimeout: 30000  #请求连接的超时时间
  MaxAutoRetries: 1   #对当前实例的重试次数
  MaxAutoRetriesNextServer: 3  #切换实例的重试次数
  eureka:
    enabled: true

properties:
  error: error.properties
 
jdbc_driver0: com.mysql.jdbc.Driver
jdbc_url0: jdbc:mysql://192.168.1.81:3306/guiyu_dispatch?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
jdbc_username0: dispatch
jdbc_password0: dispatch@1234
validationQuery: SELECT1
#xxl-job admin中心配置
xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://192.168.1.78:18016/xxl-job-admin
    executor:
      ip:
      port: 9031
      logpath: /home/logs/guiyu-dispatch-web
      logretentiondays: -1
    accessToken:

weixin:
  appid: wx1558a28a6907c3e8  #跳转到的小程序appid
  templateId: sWm0PZIGJ0EZZ0gH3n7eeT__sC1mGxqqzhHkGXwzy_s  #模板id
  pagePath:
    mainUrl:  #小程序通话详情页面
    reordListUrl:  #小程序通话记录列表页面
rabbit:
  general:
    fanout:                               #需要绑定交换机与队列关系
      exchange: fanout.dispatch.BatchImportSaveDB|fanout.dispatch.creatOrgDone #交换机名称
      queue: fanout.dispatch.BatchImportSaveDB.SAVEDB|fanout.dispatch.creatOrgDone.add #队列名称

####临时目录
file:
  tmpPath: /apps/jars/