package com.guiji.botsentence.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class BotSentenceKeywordTemplate implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_sentence_keyword_template.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_sentence_keyword_template.industry_id
     *
     * @mbggenerated
     */
    private String industryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_sentence_keyword_template.industry_name
     *
     * @mbggenerated
     */
    private String industryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_sentence_keyword_template.intent_name
     *
     * @mbggenerated
     */
    private String intentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_sentence_keyword_template.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_sentence_keyword_template.crt_time
     *
     * @mbggenerated
     */
    private Date crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_sentence_keyword_template.crt_user
     *
     * @mbggenerated
     */
    private String crtUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bot_sentence_keyword_template.keywords
     *
     * @mbggenerated
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bot_sentence_keyword_template
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_sentence_keyword_template.id
     *
     * @return the value of bot_sentence_keyword_template.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_sentence_keyword_template.id
     *
     * @param id the value for bot_sentence_keyword_template.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_sentence_keyword_template.industry_id
     *
     * @return the value of bot_sentence_keyword_template.industry_id
     *
     * @mbggenerated
     */
    public String getIndustryId() {
        return industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_sentence_keyword_template.industry_id
     *
     * @param industryId the value for bot_sentence_keyword_template.industry_id
     *
     * @mbggenerated
     */
    public void setIndustryId(String industryId) {
        this.industryId = industryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_sentence_keyword_template.industry_name
     *
     * @return the value of bot_sentence_keyword_template.industry_name
     *
     * @mbggenerated
     */
    public String getIndustryName() {
        return industryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_sentence_keyword_template.industry_name
     *
     * @param industryName the value for bot_sentence_keyword_template.industry_name
     *
     * @mbggenerated
     */
    public void setIndustryName(String industryName) {
        this.industryName = industryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_sentence_keyword_template.intent_name
     *
     * @return the value of bot_sentence_keyword_template.intent_name
     *
     * @mbggenerated
     */
    public String getIntentName() {
        return intentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_sentence_keyword_template.intent_name
     *
     * @param intentName the value for bot_sentence_keyword_template.intent_name
     *
     * @mbggenerated
     */
    public void setIntentName(String intentName) {
        this.intentName = intentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_sentence_keyword_template.type
     *
     * @return the value of bot_sentence_keyword_template.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_sentence_keyword_template.type
     *
     * @param type the value for bot_sentence_keyword_template.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_sentence_keyword_template.crt_time
     *
     * @return the value of bot_sentence_keyword_template.crt_time
     *
     * @mbggenerated
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_sentence_keyword_template.crt_time
     *
     * @param crtTime the value for bot_sentence_keyword_template.crt_time
     *
     * @mbggenerated
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_sentence_keyword_template.crt_user
     *
     * @return the value of bot_sentence_keyword_template.crt_user
     *
     * @mbggenerated
     */
    public String getCrtUser() {
        return crtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_sentence_keyword_template.crt_user
     *
     * @param crtUser the value for bot_sentence_keyword_template.crt_user
     *
     * @mbggenerated
     */
    public void setCrtUser(String crtUser) {
        this.crtUser = crtUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bot_sentence_keyword_template.keywords
     *
     * @return the value of bot_sentence_keyword_template.keywords
     *
     * @mbggenerated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bot_sentence_keyword_template.keywords
     *
     * @param keywords the value for bot_sentence_keyword_template.keywords
     *
     * @mbggenerated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }
}