server:
  id: 1  #不同fsmanager需修改为不一样的，取值范围1至1023
  port: 19021

spring:
  application:
    name: guiyu-callcenter-fsmanager
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 192.168.1.81 # Redis服务器地址
    #host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 5000 # 连接超时时间（毫秒）
    pool:
      max-active: 400 # 连接池最大连接数（使用负值表示没有限制
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 300 # 连接池中的最大空闲连接
      min-idle: 100 # 连接池中的最小空闲连接
  rabbitmq:
    host: 192.168.1.81
    port: 5672
    virtual-host: /
    username: guiyu
    password: 123456
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.5

endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
jdbc_driver0: com.mysql.jdbc.Driver
#jdbc_url0: jdbc:mysql://192.168.1.81:3306/guiyu_callcenter?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#jdbc_username0: callcenter
#jdbc_password0: callcenter@1234
jdbc_url0: jdbc:mysql://127.0.0.1:3306/guiyu_callcenter?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
jdbc_username0: root
jdbc_password0: root
validationQuery: SELECT 1
#数据库连接配置
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
jdbc:
  type: mysql

#注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://guiyu-cloud-registeration:18001/eureka/

gateway:
  username: user
  password: pwd

properties:
  error: properties/error.properties

rabbit:
  general:
    fanout:
      exchange: fanoutLineNoticeBindExchange

