// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.guiji.process.core.message;

public final class CmdProtoMessage {
  private CmdProtoMessage() {}
  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
          com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoMessageOrBuilder extends
          // @@protoc_insertion_point(interface_extends:ProtoMessage)
          com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string reqKey = 1;</code>
     */
    String getReqKey();
    /**
     * <code>string reqKey = 1;</code>
     */
    com.google.protobuf.ByteString
    getReqKeyBytes();

    /**
     * <code>int32 msgType = 2;</code>
     */
    int getMsgType();

    /**
     * <code>int32 cmdType = 3;</code>
     */
    int getCmdType();

    /**
     * <code>string parameters = 4;</code>
     */
    String getParameters();
    /**
     * <code>string parameters = 4;</code>
     */
    com.google.protobuf.ByteString
    getParametersBytes();

    /**
     * <code>int32 port = 5;</code>
     */
    int getPort();

    /**
     * <code>int32 processType = 6;</code>
     */
    int getProcessType();

    /**
     * <code>string processKey = 7;</code>
     */
    String getProcessKey();
    /**
     * <code>string processKey = 7;</code>
     */
    com.google.protobuf.ByteString
    getProcessKeyBytes();

    /**
     * <code>int32 status = 8;</code>
     */
    int getStatus();

    /**
     * <code>int32 type = 9;</code>
     */
    int getType();

    /**
     * <code>string id = 10;</code>
     */
    String getId();
    /**
     * <code>string id = 10;</code>
     */
    com.google.protobuf.ByteString
    getIdBytes();

    /**
     * <code>string content = 11;</code>
     */
    String getContent();
    /**
     * <code>string content = 11;</code>
     */
    com.google.protobuf.ByteString
    getContentBytes();

    /**
     * <code>string cmdResult = 12;</code>
     */
    String getCmdResult();
    /**
     * <code>string cmdResult = 12;</code>
     */
    com.google.protobuf.ByteString
    getCmdResultBytes();

    /**
     * <code>string cmdResultDesc = 13;</code>
     */
    String getCmdResultDesc();
    /**
     * <code>string cmdResultDesc = 13;</code>
     */
    com.google.protobuf.ByteString
    getCmdResultDescBytes();

    /**
     * <code>string name = 14;</code>
     */
    String getName();
    /**
     * <code>string name = 14;</code>
     */
    com.google.protobuf.ByteString
    getNameBytes();
  }
  /**
   * Protobuf type {@code ProtoMessage}
   */
  public  static final class ProtoMessage extends
          com.google.protobuf.GeneratedMessageV3 implements
          // @@protoc_insertion_point(message_implements:ProtoMessage)
          ProtoMessageOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use ProtoMessage.newBuilder() to construct.
    private ProtoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoMessage() {
      reqKey_ = "";
      msgType_ = -1;
      cmdType_ = -1;
      parameters_ = "";
      port_ = -1;
      processType_ = -1;
      processKey_ = "";
      status_ = -1;
      type_ = 0;
      id_ = "";
      content_ = "";
      cmdResult_ = "";
      cmdResultDesc_ = "";
      name_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoMessage(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              reqKey_ = s;
              break;
            }
            case 16: {

              msgType_ = input.readInt32();
              break;
            }
            case 24: {

              cmdType_ = input.readInt32();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              parameters_ = s;
              break;
            }
            case 40: {

              port_ = input.readInt32();
              break;
            }
            case 48: {

              processType_ = input.readInt32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              processKey_ = s;
              break;
            }
            case 64: {

              status_ = input.readInt32();
              break;
            }
            case 72: {

              type_ = input.readInt32();
              break;
            }
            case 82: {
              String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 90: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 98: {
              String s = input.readStringRequireUtf8();

              cmdResult_ = s;
              break;
            }
            case 106: {
              String s = input.readStringRequireUtf8();

              cmdResultDesc_ = s;
              break;
            }
            case 114: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                      input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
                e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return CmdProtoMessage.internal_static_ProtoMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
      return CmdProtoMessage.internal_static_ProtoMessage_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                      ProtoMessage.class, Builder.class);
    }

    public static final int REQKEY_FIELD_NUMBER = 1;
    private volatile Object reqKey_;
    /**
     * <code>string reqKey = 1;</code>
     */
    public String getReqKey() {
      Object ref = reqKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        reqKey_ = s;
        return s;
      }
    }
    /**
     * <code>string reqKey = 1;</code>
     */
    public com.google.protobuf.ByteString
    getReqKeyBytes() {
      Object ref = reqKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        reqKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGTYPE_FIELD_NUMBER = 2;
    private int msgType_;
    /**
     * <code>int32 msgType = 2;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int CMDTYPE_FIELD_NUMBER = 3;
    private int cmdType_;
    /**
     * <code>int32 cmdType = 3;</code>
     */
    public int getCmdType() {
      return cmdType_;
    }

    public static final int PARAMETERS_FIELD_NUMBER = 4;
    private volatile Object parameters_;
    /**
     * <code>string parameters = 4;</code>
     */
    public String getParameters() {
      Object ref = parameters_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        parameters_ = s;
        return s;
      }
    }
    /**
     * <code>string parameters = 4;</code>
     */
    public com.google.protobuf.ByteString
    getParametersBytes() {
      Object ref = parameters_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        parameters_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 5;
    private int port_;
    /**
     * <code>int32 port = 5;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int PROCESSTYPE_FIELD_NUMBER = 6;
    private int processType_;
    /**
     * <code>int32 processType = 6;</code>
     */
    public int getProcessType() {
      return processType_;
    }

    public static final int PROCESSKEY_FIELD_NUMBER = 7;
    private volatile Object processKey_;
    /**
     * <code>string processKey = 7;</code>
     */
    public String getProcessKey() {
      Object ref = processKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        processKey_ = s;
        return s;
      }
    }
    /**
     * <code>string processKey = 7;</code>
     */
    public com.google.protobuf.ByteString
    getProcessKeyBytes() {
      Object ref = processKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        processKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 8;
    private int status_;
    /**
     * <code>int32 status = 8;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int TYPE_FIELD_NUMBER = 9;
    private int type_;
    /**
     * <code>int32 type = 9;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int ID_FIELD_NUMBER = 10;
    private volatile Object id_;
    /**
     * <code>string id = 10;</code>
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 10;</code>
     */
    public com.google.protobuf.ByteString
    getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 11;
    private volatile Object content_;
    /**
     * <code>string content = 11;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 11;</code>
     */
    public com.google.protobuf.ByteString
    getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMDRESULT_FIELD_NUMBER = 12;
    private volatile Object cmdResult_;
    /**
     * <code>string cmdResult = 12;</code>
     */
    public String getCmdResult() {
      Object ref = cmdResult_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cmdResult_ = s;
        return s;
      }
    }
    /**
     * <code>string cmdResult = 12;</code>
     */
    public com.google.protobuf.ByteString
    getCmdResultBytes() {
      Object ref = cmdResult_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        cmdResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMDRESULTDESC_FIELD_NUMBER = 13;
    private volatile Object cmdResultDesc_;
    /**
     * <code>string cmdResultDesc = 13;</code>
     */
    public String getCmdResultDesc() {
      Object ref = cmdResultDesc_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cmdResultDesc_ = s;
        return s;
      }
    }
    /**
     * <code>string cmdResultDesc = 13;</code>
     */
    public com.google.protobuf.ByteString
    getCmdResultDescBytes() {
      Object ref = cmdResultDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        cmdResultDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 14;
    private volatile Object name_;
    /**
     * <code>string name = 14;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 14;</code>
     */
    public com.google.protobuf.ByteString
    getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                        (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
      if (!getReqKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, reqKey_);
      }
      if (msgType_ != -1) {
        output.writeInt32(2, msgType_);
      }
      if (cmdType_ != -1) {
        output.writeInt32(3, cmdType_);
      }
      if (!getParametersBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, parameters_);
      }
      if (port_ != 0) {
        output.writeInt32(5, port_);
      }
      if (processType_ != -1) {
        output.writeInt32(6, processType_);
      }
      if (!getProcessKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, processKey_);
      }
      if (status_ != -1) {
        output.writeInt32(8, status_);
      }
      if (type_ != 0) {
        output.writeInt32(9, type_);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, id_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, content_);
      }
      if (!getCmdResultBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, cmdResult_);
      }
      if (!getCmdResultDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, cmdResultDesc_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, name_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getReqKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, reqKey_);
      }
      if (msgType_ != -1) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(2, msgType_);
      }
      if (cmdType_ != -1) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(3, cmdType_);
      }
      if (!getParametersBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, parameters_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(5, port_);
      }
      if (processType_ != -1) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(6, processType_);
      }
      if (!getProcessKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, processKey_);
      }
      if (status_ != -1) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(8, status_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
                .computeInt32Size(9, type_);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, id_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, content_);
      }
      if (!getCmdResultBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, cmdResult_);
      }
      if (!getCmdResultDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, cmdResultDesc_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof ProtoMessage)) {
        return super.equals(obj);
      }
      ProtoMessage other = (ProtoMessage) obj;

      boolean result = true;
      result = result && getReqKey()
              .equals(other.getReqKey());
      result = result && (getMsgType()
              == other.getMsgType());
      result = result && (getCmdType()
              == other.getCmdType());
      result = result && getParameters()
              .equals(other.getParameters());
      result = result && (getPort()
              == other.getPort());
      result = result && (getProcessType()
              == other.getProcessType());
      result = result && getProcessKey()
              .equals(other.getProcessKey());
      result = result && (getStatus()
              == other.getStatus());
      result = result && (getType()
              == other.getType());
      result = result && getId()
              .equals(other.getId());
      result = result && getContent()
              .equals(other.getContent());
      result = result && getCmdResult()
              .equals(other.getCmdResult());
      result = result && getCmdResultDesc()
              .equals(other.getCmdResultDesc());
      result = result && getName()
              .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQKEY_FIELD_NUMBER;
      hash = (53 * hash) + getReqKey().hashCode();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType();
      hash = (37 * hash) + CMDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCmdType();
      hash = (37 * hash) + PARAMETERS_FIELD_NUMBER;
      hash = (53 * hash) + getParameters().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + PROCESSTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getProcessType();
      hash = (37 * hash) + PROCESSKEY_FIELD_NUMBER;
      hash = (53 * hash) + getProcessKey().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + CMDRESULT_FIELD_NUMBER;
      hash = (53 * hash) + getCmdResult().hashCode();
      hash = (37 * hash) + CMDRESULTDESC_FIELD_NUMBER;
      hash = (53 * hash) + getCmdResultDesc().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoMessage parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoMessage parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoMessage parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoMessage parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoMessage parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoMessage parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoMessage parseFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static ProtoMessage parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoMessage parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoMessage parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoMessage parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input);
    }
    public static ProtoMessage parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
              .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
              ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoMessage}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:ProtoMessage)
            ProtoMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return CmdProtoMessage.internal_static_ProtoMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
      internalGetFieldAccessorTable() {
        return CmdProtoMessage.internal_static_ProtoMessage_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        ProtoMessage.class, Builder.class);
      }

      // Construct using com.guiji.process.core.message.CmdProtoMessage.ProtoMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
              BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        reqKey_ = "";

        msgType_ = -1;

        cmdType_ = -1;

        parameters_ = "";

        port_ = -1;

        processType_ = -1;

        processKey_ = "";

        status_ = -1;

        type_ = 0;

        id_ = "";

        content_ = "";

        cmdResult_ = "";

        cmdResultDesc_ = "";

        name_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return CmdProtoMessage.internal_static_ProtoMessage_descriptor;
      }

      @Override
      public ProtoMessage getDefaultInstanceForType() {
        return ProtoMessage.getDefaultInstance();
      }

      @Override
      public ProtoMessage build() {
        ProtoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ProtoMessage buildPartial() {
        ProtoMessage result = new ProtoMessage(this);
        result.reqKey_ = reqKey_;
        result.msgType_ = msgType_;
        result.cmdType_ = cmdType_;
        result.parameters_ = parameters_;
        result.port_ = port_;
        result.processType_ = processType_;
        result.processKey_ = processKey_;
        result.status_ = status_;
        result.type_ = type_;
        result.id_ = id_;
        result.content_ = content_;
        result.cmdResult_ = cmdResult_;
        result.cmdResultDesc_ = cmdResultDesc_;
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
              com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
              com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
              com.google.protobuf.Descriptors.FieldDescriptor field,
              Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoMessage) {
          return mergeFrom((ProtoMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoMessage other) {
        if (other == ProtoMessage.getDefaultInstance()) return this;
        if (!other.getReqKey().isEmpty()) {
          reqKey_ = other.reqKey_;
          onChanged();
        }
        if (other.getMsgType() != -1) {
          setMsgType(other.getMsgType());
        }
        if (other.getCmdType() != -1) {
          setCmdType(other.getCmdType());
        }
        if (!other.getParameters().isEmpty()) {
          parameters_ = other.parameters_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.getProcessType() != -1) {
          setProcessType(other.getProcessType());
        }
        if (!other.getProcessKey().isEmpty()) {
          processKey_ = other.processKey_;
          onChanged();
        }
        if (other.getStatus() != -1) {
          setStatus(other.getStatus());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (!other.getCmdResult().isEmpty()) {
          cmdResult_ = other.cmdResult_;
          onChanged();
        }
        if (!other.getCmdResultDesc().isEmpty()) {
          cmdResultDesc_ = other.cmdResultDesc_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        ProtoMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object reqKey_ = "";
      /**
       * <code>string reqKey = 1;</code>
       */
      public String getReqKey() {
        Object ref = reqKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          reqKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string reqKey = 1;</code>
       */
      public com.google.protobuf.ByteString
      getReqKeyBytes() {
        Object ref = reqKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          reqKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reqKey = 1;</code>
       */
      public Builder setReqKey(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        reqKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reqKey = 1;</code>
       */
      public Builder clearReqKey() {

        reqKey_ = getDefaultInstance().getReqKey();
        onChanged();
        return this;
      }
      /**
       * <code>string reqKey = 1;</code>
       */
      public Builder setReqKeyBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        reqKey_ = value;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <code>int32 msgType = 2;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <code>int32 msgType = 2;</code>
       */
      public Builder setMsgType(int value) {

        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 msgType = 2;</code>
       */
      public Builder clearMsgType() {

        msgType_ = -1;
        onChanged();
        return this;
      }

      private int cmdType_ ;
      /**
       * <code>int32 cmdType = 3;</code>
       */
      public int getCmdType() {
        return cmdType_;
      }
      /**
       * <code>int32 cmdType = 3;</code>
       */
      public Builder setCmdType(int value) {

        cmdType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cmdType = 3;</code>
       */
      public Builder clearCmdType() {

        cmdType_ = -1;
        onChanged();
        return this;
      }

      private Object parameters_ = "";
      /**
       * <code>string parameters = 4;</code>
       */
      public String getParameters() {
        Object ref = parameters_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          parameters_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string parameters = 4;</code>
       */
      public com.google.protobuf.ByteString
      getParametersBytes() {
        Object ref = parameters_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          parameters_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string parameters = 4;</code>
       */
      public Builder setParameters(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        parameters_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string parameters = 4;</code>
       */
      public Builder clearParameters() {

        parameters_ = getDefaultInstance().getParameters();
        onChanged();
        return this;
      }
      /**
       * <code>string parameters = 4;</code>
       */
      public Builder setParametersBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        parameters_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 5;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 5;</code>
       */
      public Builder setPort(int value) {

        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 5;</code>
       */
      public Builder clearPort() {

        port_ = 0;
        onChanged();
        return this;
      }

      private int processType_ ;
      /**
       * <code>int32 processType = 6;</code>
       */
      public int getProcessType() {
        return processType_;
      }
      /**
       * <code>int32 processType = 6;</code>
       */
      public Builder setProcessType(int value) {

        processType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 processType = 6;</code>
       */
      public Builder clearProcessType() {

        processType_ = -1;
        onChanged();
        return this;
      }

      private Object processKey_ = "";
      /**
       * <code>string processKey = 7;</code>
       */
      public String getProcessKey() {
        Object ref = processKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          processKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string processKey = 7;</code>
       */
      public com.google.protobuf.ByteString
      getProcessKeyBytes() {
        Object ref = processKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          processKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string processKey = 7;</code>
       */
      public Builder setProcessKey(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        processKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string processKey = 7;</code>
       */
      public Builder clearProcessKey() {

        processKey_ = getDefaultInstance().getProcessKey();
        onChanged();
        return this;
      }
      /**
       * <code>string processKey = 7;</code>
       */
      public Builder setProcessKeyBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        processKey_ = value;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 8;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 8;</code>
       */
      public Builder setStatus(int value) {

        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 8;</code>
       */
      public Builder clearStatus() {

        status_ = -1;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 9;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 9;</code>
       */
      public Builder setType(int value) {

        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 9;</code>
       */
      public Builder clearType() {

        type_ = 0;
        onChanged();
        return this;
      }

      private Object id_ = "";
      /**
       * <code>string id = 10;</code>
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string id = 10;</code>
       */
      public com.google.protobuf.ByteString
      getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 10;</code>
       */
      public Builder setId(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 10;</code>
       */
      public Builder clearId() {

        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 10;</code>
       */
      public Builder setIdBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        id_ = value;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>string content = 11;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content = 11;</code>
       */
      public com.google.protobuf.ByteString
      getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 11;</code>
       */
      public Builder setContent(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 11;</code>
       */
      public Builder clearContent() {

        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 11;</code>
       */
      public Builder setContentBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        content_ = value;
        onChanged();
        return this;
      }

      private Object cmdResult_ = "";
      /**
       * <code>string cmdResult = 12;</code>
       */
      public String getCmdResult() {
        Object ref = cmdResult_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          cmdResult_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string cmdResult = 12;</code>
       */
      public com.google.protobuf.ByteString
      getCmdResultBytes() {
        Object ref = cmdResult_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          cmdResult_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cmdResult = 12;</code>
       */
      public Builder setCmdResult(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        cmdResult_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cmdResult = 12;</code>
       */
      public Builder clearCmdResult() {

        cmdResult_ = getDefaultInstance().getCmdResult();
        onChanged();
        return this;
      }
      /**
       * <code>string cmdResult = 12;</code>
       */
      public Builder setCmdResultBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        cmdResult_ = value;
        onChanged();
        return this;
      }

      private Object cmdResultDesc_ = "";
      /**
       * <code>string cmdResultDesc = 13;</code>
       */
      public String getCmdResultDesc() {
        Object ref = cmdResultDesc_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          cmdResultDesc_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string cmdResultDesc = 13;</code>
       */
      public com.google.protobuf.ByteString
      getCmdResultDescBytes() {
        Object ref = cmdResultDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          cmdResultDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cmdResultDesc = 13;</code>
       */
      public Builder setCmdResultDesc(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        cmdResultDesc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cmdResultDesc = 13;</code>
       */
      public Builder clearCmdResultDesc() {

        cmdResultDesc_ = getDefaultInstance().getCmdResultDesc();
        onChanged();
        return this;
      }
      /**
       * <code>string cmdResultDesc = 13;</code>
       */
      public Builder setCmdResultDescBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        cmdResultDesc_ = value;
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 14;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
                  (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 14;</code>
       */
      public com.google.protobuf.ByteString
      getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
                  com.google.protobuf.ByteString.copyFromUtf8(
                          (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 14;</code>
       */
      public Builder setName(
              String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 14;</code>
       */
      public Builder clearName() {

        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 14;</code>
       */
      public Builder setNameBytes(
              com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        name_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ProtoMessage)
    }

    // @@protoc_insertion_point(class_scope:ProtoMessage)
    private static final ProtoMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoMessage();
    }

    public static ProtoMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoMessage>
            PARSER = new com.google.protobuf.AbstractParser<ProtoMessage>() {
      @Override
      public ProtoMessage parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ProtoMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public ProtoMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
          internal_static_ProtoMessage_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internal_static_ProtoMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
          descriptor;
  static {
    String[] descriptorData = {
            "\n\rMessage.proto\"\376\001\n\014ProtoMessage\022\016\n\006reqK" +
                    "ey\030\001 \001(\t\022\017\n\007msgType\030\002 \001(\005\022\017\n\007cmdType\030\003 \001" +
                    "(\005\022\022\n\nparameters\030\004 \001(\t\022\014\n\004port\030\005 \001(\005\022\023\n\013" +
                    "processType\030\006 \001(\005\022\022\n\nprocessKey\030\007 \001(\t\022\016\n" +
                    "\006status\030\010 \001(\005\022\014\n\004type\030\t \001(\005\022\n\n\002id\030\n \001(\t\022" +
                    "\017\n\007content\030\013 \001(\t\022\021\n\tcmdResult\030\014 \001(\t\022\025\n\rc" +
                    "mdResultDesc\030\r \001(\t\022\014\n\004name\030\016 \001(\tB1\n\036com." +
                    "guiji.process.core.messageB\017CmdProtoMess" +
                    "ageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
              public com.google.protobuf.ExtensionRegistry assignDescriptors(
                      com.google.protobuf.Descriptors.FileDescriptor root) {
                descriptor = root;
                return null;
              }
            };
    com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                    new com.google.protobuf.Descriptors.FileDescriptor[] {
                    }, assigner);
    internal_static_ProtoMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_ProtoMessage_descriptor,
            new String[] { "ReqKey", "MsgType", "CmdType", "Parameters", "Port", "ProcessType", "ProcessKey", "Status", "Type", "Id", "Content", "CmdResult", "CmdResultDesc", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
