server:
  port: 18017

spring:
  application:
    name: guiyu-sms-web
  datasource:  
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.1.57:3306/guiyu_sms?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&allowMultiQueries=true
    username: sms
    password: sms@1234
    driver-class-name: com.mysql.jdbc.Driver 
    minIdle: 5  
    maxActive: 200  
    initialSize: 5 
    timeBetweenEvictionRunsMillis: 3000  
    minEvictableIdleTimeMillis: 300000  
    validationQuery: SELECT 'ZTM' FROM DUAL  
    testWhileIdle: true  
    testOnBorrow: false  
    testOnReturn: false
  redis:
    database: 8
    host: 192.168.1.81
    port: 6379
    password: 123456
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.5

endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false

 
#数据库连接配置
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
jdbc:
  type: mysql


#注册中心配置      
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://guiyu-cloud-registeration:18001/eureka/

#网关地址
gateway:
  host: http://guiyu-cloud-zuul:18000/


properties:
  error: properties/error.properties
  

rabbit:
  general:
    direct:
      queues: SendMessageMQ.direct.Sms|SendMessageTaskMQ.direct.Sms


