server:
  port: 18003
spring:
  application:
    name: guiyu-cloud-monitor
zipkin:
  collector:
    rabbitmq:
      addresses: 192.168.1.81:5672
      password: 123456
      username: guiyu
      queue: zipkin
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://guiyu-cloud-registeration:18001/eureka/
endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
turbine:
  app-config-list: micro-a-service
  cluster-name-expression: "'default'"