server:
  port: 18051

spring:
  application:
    name: guiyu-ai-web
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.5

endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false


#注册中心配置      
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://guiyu-cloud-registeration:18001/eureka/

#网关地址
gateway:
  host: http://guiyu-cloud-zuul:18000/


properties:
  error: properties/error.properties


guiyu_tts_2_url: http://localhost:38002/ # guiyu-tts2.0服务地址
notifyAiUrl: http://localhost:18051/callback # ai服务地址

