server:
  port: 18071
spring:
  application:
    name: guiyu-botstence-web
  http:
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 100MB # 设置单个文件的最大长度
      max-request-size: 100MB # 设置最大的请求文件的大小
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /  # 上传的临时目录     
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource  
    url: jdbc:mysql://192.168.1.81:3306/guiyu_botstence?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&allowMultiQueries=true
    username: root
    password: Root@123456
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 5
    maxActive: 200
    initialSize: 5
    timeBetweenEvictionRunsMillis: 3000  
    minEvictableIdleTimeMillis: 300000  
    validationQuery: SELECT 'ZTM' FROM DUAL  
    testWhileIdle: true  
    testOnBorrow: false  
    testOnReturn: false    
  redis:
    database: 0
    host: 192.168.1.78
    password: 123456
    port: 6379
    pool:
      max-active: 400
      max-wait: -1
      min-idle: 100
      max-idle: 300
  rabbitmq:
    host: 192.168.1.81
    port: 5672
    virtual-host: /
    username: guiyu
    password: 123456
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.5

endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
        
      
#数据库连接配置
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
jdbc:
  type: mysql      

#注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://guiyu-cloud-registeration:18001/eureka/
    instance:
      status-page-url: http://localhost:18000/eureka//swagger-ui.html
##网关地址
gateway:
  host: http://guiyu-cloud-zuul:18000/

ribbon:
  ReadTimeout: 30000 #请求处理的超时时间
  ConnectTimeout: 30000  #请求连接的超时时间
  MaxAutoRetries: 0   #对当前实例的重试次数
  MaxAutoRetriesNextServer: 1  #切换实例的重试次数
  eureka:
    enabled: true

logging:
  config: classpath:logback.xml
  level:
    org:
      springframework:
        web: info

properties:
  error: properties/error.properties


rabbit:
  general:
    fanout:
      exchange: fanoutSpeechAuditExchange
      queue: fanoutSpeechAuditQueue

offline: false
local.wav.dir: /usr/local/botsentence/html/static/wavs/
local.wav.dir.pre: /usr/local/botsentence/html
sellbot.mechine: 
  mechineList: 
    - ip: 192.168.1.86
      username: root
      password: 123456
      path: /home/sellbot/dist/app

selftest.sellbot:
  serverUrl: 192.168.1.81
  innerUrl: 192.168.1.81
  serverStartPort: 15000
  serverPortCount: 32
  username: root
  password: 123456
  path: /home/sellbot/dist/app
  port: 22



#七牛云配置
qn: 
  enable: true
  accessKey: 8nRNpj2TQ-7CagTHycDSikETfq-1apf-u3fQe8wx
  secretKey: RZlH2vWVY-P_Gius2fRlHlC8BqMJ1WVOiUYtTCki
  bucket: xiangce
  path: https://yuyin.guiji.ai/
  
#sftp部署
sftp: 
  enable: true
  username: talk-temp
  password: 123456
  host: 47.99.106.54
  port: 18032
  path: /var/version/talk/
  requestPath: http://47.99.106.54:8888/talk/
  
#存放模板配置文件路径
template.dir: /home/botsentence/template
export.dir: /home/botsentence/template_new
create.file.tmp: /home/botsentence/fileTemp
template.copyfiles.dir: /home/botsentence/template/copyfiles
local.upload.dir: /home/botsentence/template_encode/
upload.cfgs.dir: /home/botsentence/cfgs
standard.head.dir: /home/botsentence/cfgs/standard_head.wav
check.agent.dir: /usr/local/botsentence

autoDeploy.path: http://47.99.106.54:12000/add/task
autoDeploy.token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ0dHMiLCJpYXQiOjE1MzMwMzgxMTksInB1YmxpY19pZCI6IjE2OGYxNjUwLWIyMTUtNDgyZS05M2E1LWZmODYzMDU0YTVmOCIsImV4cCI6MTg0ODM5OTkxOX0.TIZVlNp5MGA0jL72Htvg_BB9Ltca_zzHaRV81CkyIE4


#上传tts模板replace.json的路径 
tts.sftp.username: root
tts.sftp.password: 50xfswsscqdb!
tts.sftp.host: 47.96.79.114
tts.sftp.port: 22
tts.sftp.path: /root/cfgs/

#TTS合成接口
all_tts: false
tts.api.url: http://47.96.79.114:10000/poc/wav

#硅基快配置小程序
wechat.appid: wx6b74c97d21bf735c
wechat.secret: 00078045f8a8483beb734f8cc90b47f8

