package com.guiji.callcenter.dao;


import com.guiji.callcenter.dao.entity.Agent;
import com.guiji.callcenter.dao.entity.AgentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AgentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbggenerated
     */
    int countByExample(AgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbggenerated
     */
    int deleteByExample(AgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbggenerated
     */
    int insert(Agent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbggenerated
     */
    int insertSelective(Agent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbggenerated
     */
    List<Agent> selectByExample(AgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbggenerated
     */
    Agent selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Agent record, @Param("example") AgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Agent record, @Param("example") AgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Agent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agent
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Agent record);

    Long selectMaxUserId();

    Long selectMinUserId();
}