package com.guiji.callcenter.dao;


import com.guiji.callcenter.dao.entity.LineConfig;
import com.guiji.callcenter.dao.entity.LineConfigExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LineConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_config
     *
     * @mbggenerated
     */
    int countByExample(LineConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_config
     *
     * @mbggenerated
     */
    int deleteByExample(LineConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_config
     *
     * @mbggenerated
     */
    int insert(LineConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_config
     *
     * @mbggenerated
     */
    int insertSelective(LineConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_config
     *
     * @mbggenerated
     */
    List<LineConfig> selectByExample(LineConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_config
     *
     * @mbggenerated
     */
    LineConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_config
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LineConfig record, @Param("example") LineConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_config
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LineConfig record, @Param("example") LineConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LineConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table line_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LineConfig record);
}