package com.guiji.callcenter.dao;


import com.guiji.callcenter.dao.entity.Registration;
import com.guiji.callcenter.dao.entity.RegistrationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RegistrationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated
     */
    int countByExample(RegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated
     */
    int deleteByExample(RegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long regId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated
     */
    int insert(Registration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated
     */
    int insertSelective(Registration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated
     */
    List<Registration> selectByExample(RegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated
     */
    Registration selectByPrimaryKey(Long regId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Registration record, @Param("example") RegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Registration record, @Param("example") RegistrationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Registration record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table registration
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Registration record);

    /**
     * 批量删除
     * @param list
     */
    void  batchdeleteRegistration(List<Long> list);
}