package com.guiji.callcenter.dao;

import com.guiji.callcenter.dao.entity.Tier;
import com.guiji.callcenter.dao.entity.TierExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tier
     *
     * @mbggenerated
     */
    int countByExample(TierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tier
     *
     * @mbggenerated
     */
    int deleteByExample(TierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tier
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tier
     *
     * @mbggenerated
     */
    int insert(Tier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tier
     *
     * @mbggenerated
     */
    int insertSelective(Tier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tier
     *
     * @mbggenerated
     */
    List<Tier> selectByExample(TierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tier
     *
     * @mbggenerated
     */
    Tier selectByPrimaryKey(Long tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tier
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Tier record, @Param("example") TierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tier
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Tier record, @Param("example") TierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tier
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Tier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tier
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Tier record);
}