package com.guiji.callcenter.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class Agent implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.crm_login_id
     *
     * @mbggenerated
     */
    private String crmLoginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.answer_type
     *
     * @mbggenerated
     */
    private Integer answerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.creator
     *
     * @mbggenerated
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.update_user
     *
     * @mbggenerated
     */
    private Long updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.user_name
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.user_pwd
     *
     * @mbggenerated
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.user_role
     *
     * @mbggenerated
     */
    private Integer userRole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.user_state
     *
     * @mbggenerated
     */
    private Integer userState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.org_code
     *
     * @mbggenerated
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.customer_id
     *
     * @mbggenerated
     */
    private Long customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table agent
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.user_id
     *
     * @return the value of agent.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.user_id
     *
     * @param userId the value for agent.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.crm_login_id
     *
     * @return the value of agent.crm_login_id
     *
     * @mbggenerated
     */
    public String getCrmLoginId() {
        return crmLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.crm_login_id
     *
     * @param crmLoginId the value for agent.crm_login_id
     *
     * @mbggenerated
     */
    public void setCrmLoginId(String crmLoginId) {
        this.crmLoginId = crmLoginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.answer_type
     *
     * @return the value of agent.answer_type
     *
     * @mbggenerated
     */
    public Integer getAnswerType() {
        return answerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.answer_type
     *
     * @param answerType the value for agent.answer_type
     *
     * @mbggenerated
     */
    public void setAnswerType(Integer answerType) {
        this.answerType = answerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.create_time
     *
     * @return the value of agent.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.create_time
     *
     * @param createTime the value for agent.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.creator
     *
     * @return the value of agent.creator
     *
     * @mbggenerated
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.creator
     *
     * @param creator the value for agent.creator
     *
     * @mbggenerated
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.mobile
     *
     * @return the value of agent.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.mobile
     *
     * @param mobile the value for agent.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.update_time
     *
     * @return the value of agent.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.update_time
     *
     * @param updateTime the value for agent.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.update_user
     *
     * @return the value of agent.update_user
     *
     * @mbggenerated
     */
    public Long getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.update_user
     *
     * @param updateUser the value for agent.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(Long updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.user_name
     *
     * @return the value of agent.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.user_name
     *
     * @param userName the value for agent.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.user_pwd
     *
     * @return the value of agent.user_pwd
     *
     * @mbggenerated
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.user_pwd
     *
     * @param userPwd the value for agent.user_pwd
     *
     * @mbggenerated
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.user_role
     *
     * @return the value of agent.user_role
     *
     * @mbggenerated
     */
    public Integer getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.user_role
     *
     * @param userRole the value for agent.user_role
     *
     * @mbggenerated
     */
    public void setUserRole(Integer userRole) {
        this.userRole = userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.user_state
     *
     * @return the value of agent.user_state
     *
     * @mbggenerated
     */
    public Integer getUserState() {
        return userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.user_state
     *
     * @param userState the value for agent.user_state
     *
     * @mbggenerated
     */
    public void setUserState(Integer userState) {
        this.userState = userState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.org_code
     *
     * @return the value of agent.org_code
     *
     * @mbggenerated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.org_code
     *
     * @param orgCode the value for agent.org_code
     *
     * @mbggenerated
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.customer_id
     *
     * @return the value of agent.customer_id
     *
     * @mbggenerated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.customer_id
     *
     * @param customerId the value for agent.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }
}