package com.guiji.callcenter.dao.entity;

import java.io.Serializable;

public class LineConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_config.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_config.line_id
     *
     * @mbggenerated
     */
    private String lineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_config.file_type
     *
     * @mbggenerated
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_config.file_name
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_config.file_data
     *
     * @mbggenerated
     */
    private String fileData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column line_config.fsagent_id
     *
     * @mbggenerated
     */
    private String fsagentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table line_config
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_config.id
     *
     * @return the value of line_config.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_config.id
     *
     * @param id the value for line_config.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_config.line_id
     *
     * @return the value of line_config.line_id
     *
     * @mbggenerated
     */
    public String getLineId() {
        return lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_config.line_id
     *
     * @param lineId the value for line_config.line_id
     *
     * @mbggenerated
     */
    public void setLineId(String lineId) {
        this.lineId = lineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_config.file_type
     *
     * @return the value of line_config.file_type
     *
     * @mbggenerated
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_config.file_type
     *
     * @param fileType the value for line_config.file_type
     *
     * @mbggenerated
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_config.file_name
     *
     * @return the value of line_config.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_config.file_name
     *
     * @param fileName the value for line_config.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_config.file_data
     *
     * @return the value of line_config.file_data
     *
     * @mbggenerated
     */
    public String getFileData() {
        return fileData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_config.file_data
     *
     * @param fileData the value for line_config.file_data
     *
     * @mbggenerated
     */
    public void setFileData(String fileData) {
        this.fileData = fileData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column line_config.fsagent_id
     *
     * @return the value of line_config.fsagent_id
     *
     * @mbggenerated
     */
    public String getFsagentId() {
        return fsagentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column line_config.fsagent_id
     *
     * @param fsagentId the value for line_config.fsagent_id
     *
     * @mbggenerated
     */
    public void setFsagentId(String fsagentId) {
        this.fsagentId = fsagentId;
    }
}