package com.guiji.callcenter.dao.entity;

import java.io.Serializable;

public class Phone implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.area_code
     *
     * @mbggenerated
     */
    private String areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.isp
     *
     * @mbggenerated
     */
    private String isp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.post_code
     *
     * @mbggenerated
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.pref
     *
     * @mbggenerated
     */
    private String pref;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table phone
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.phone
     *
     * @return the value of phone.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.phone
     *
     * @param phone the value for phone.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.area_code
     *
     * @return the value of phone.area_code
     *
     * @mbggenerated
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.area_code
     *
     * @param areaCode the value for phone.area_code
     *
     * @mbggenerated
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.city
     *
     * @return the value of phone.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.city
     *
     * @param city the value for phone.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.city_code
     *
     * @return the value of phone.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.city_code
     *
     * @param cityCode the value for phone.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.isp
     *
     * @return the value of phone.isp
     *
     * @mbggenerated
     */
    public String getIsp() {
        return isp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.isp
     *
     * @param isp the value for phone.isp
     *
     * @mbggenerated
     */
    public void setIsp(String isp) {
        this.isp = isp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.post_code
     *
     * @return the value of phone.post_code
     *
     * @mbggenerated
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.post_code
     *
     * @param postCode the value for phone.post_code
     *
     * @mbggenerated
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.pref
     *
     * @return the value of phone.pref
     *
     * @mbggenerated
     */
    public String getPref() {
        return pref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.pref
     *
     * @param pref the value for phone.pref
     *
     * @mbggenerated
     */
    public void setPref(String pref) {
        this.pref = pref;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone.province
     *
     * @return the value of phone.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone.province
     *
     * @param province the value for phone.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province;
    }
}