package com.guiji.callcenter.dao.entity;

import java.io.Serializable;
import java.math.BigInteger;

public class SimGateway implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_gateway.id
     *
     * @mbggenerated
     */
    private BigInteger id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_gateway.sim_gateway_id
     *
     * @mbggenerated
     */
    private String simGatewayId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_gateway.start_count
     *
     * @mbggenerated
     */
    private Integer startCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_gateway.counts_step
     *
     * @mbggenerated
     */
    private Integer countsStep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_gateway.start_pwd
     *
     * @mbggenerated
     */
    private Integer startPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_gateway.pwd_step
     *
     * @mbggenerated
     */
    private Integer pwdStep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_gateway.count_num
     *
     * @mbggenerated
     */
    private Integer countNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sim_gateway.sim_agent_id
     *
     * @mbggenerated
     */
    private String simAgentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sim_gateway
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_gateway.id
     *
     * @return the value of sim_gateway.id
     *
     * @mbggenerated
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_gateway.id
     *
     * @param id the value for sim_gateway.id
     *
     * @mbggenerated
     */
    public void setId(BigInteger id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_gateway.sim_gateway_id
     *
     * @return the value of sim_gateway.sim_gateway_id
     *
     * @mbggenerated
     */
    public String getSimGatewayId() {
        return simGatewayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_gateway.sim_gateway_id
     *
     * @param simGatewayId the value for sim_gateway.sim_gateway_id
     *
     * @mbggenerated
     */
    public void setSimGatewayId(String simGatewayId) {
        this.simGatewayId = simGatewayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_gateway.start_count
     *
     * @return the value of sim_gateway.start_count
     *
     * @mbggenerated
     */
    public Integer getStartCount() {
        return startCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_gateway.start_count
     *
     * @param startCount the value for sim_gateway.start_count
     *
     * @mbggenerated
     */
    public void setStartCount(Integer startCount) {
        this.startCount = startCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_gateway.counts_step
     *
     * @return the value of sim_gateway.counts_step
     *
     * @mbggenerated
     */
    public Integer getCountsStep() {
        return countsStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_gateway.counts_step
     *
     * @param countsStep the value for sim_gateway.counts_step
     *
     * @mbggenerated
     */
    public void setCountsStep(Integer countsStep) {
        this.countsStep = countsStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_gateway.start_pwd
     *
     * @return the value of sim_gateway.start_pwd
     *
     * @mbggenerated
     */
    public Integer getStartPwd() {
        return startPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_gateway.start_pwd
     *
     * @param startPwd the value for sim_gateway.start_pwd
     *
     * @mbggenerated
     */
    public void setStartPwd(Integer startPwd) {
        this.startPwd = startPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_gateway.pwd_step
     *
     * @return the value of sim_gateway.pwd_step
     *
     * @mbggenerated
     */
    public Integer getPwdStep() {
        return pwdStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_gateway.pwd_step
     *
     * @param pwdStep the value for sim_gateway.pwd_step
     *
     * @mbggenerated
     */
    public void setPwdStep(Integer pwdStep) {
        this.pwdStep = pwdStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_gateway.count_num
     *
     * @return the value of sim_gateway.count_num
     *
     * @mbggenerated
     */
    public Integer getCountNum() {
        return countNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_gateway.count_num
     *
     * @param countNum the value for sim_gateway.count_num
     *
     * @mbggenerated
     */
    public void setCountNum(Integer countNum) {
        this.countNum = countNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sim_gateway.sim_agent_id
     *
     * @return the value of sim_gateway.sim_agent_id
     *
     * @mbggenerated
     */
    public String getSimAgentId() {
        return simAgentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sim_gateway.sim_agent_id
     *
     * @param simAgentId the value for sim_gateway.sim_agent_id
     *
     * @mbggenerated
     */
    public void setSimAgentId(String simAgentId) {
        this.simAgentId = simAgentId;
    }
}