server:
  port: 18012
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000
spring:
  application:
    name: guiyu-nas-web
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true   # 启用http上传处理
      max-file-size: 100MB # 设置单个文件的最大长度
      max-request-size: 100MB # 设置最大的请求文件的大小
      file-size-threshold: 1MB  # 当上传文件达到1MB的时候进行磁盘写入
      location: /  # 上传的临时目录
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.1.81:3306/guiyu_base?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&allowMultiQueries=true
      username: base
      password: base@1234
      driver-class-name: com.mysql.jdbc.Driver
      minIdle: 5
      maxActive: 200
      initialSize: 5
      timeBetweenEvictionRunsMillis: 3000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'ZTM' FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  rabbitmq:
    host: 192.168.1.81
    port: 5672
    virtual-host: /
    username: guiyu
    password: 123456
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.5

endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
  #数据库连接配置
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
jdbc:
  type: mysql
#注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://guiyu-cloud-registeration:18001/eureka/
#fastdfs配置
fdfs:
  soTimeout: 15000         #获取文件超时时间
  connectTimeout: 6000     #连接超时时间
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 192.168.1.83:22122
  pool:
    #jmx-enabled: false
    max-total: 500
    max-wait-millis: 120
  webServerUrl: http://192.168.1.83:8080/
rabbit:
  general:
    direct:
      queue: aliyunUploadQueue|nasFileDeleteQueue #队列名称
properties:
  error: properties/error.properties
#阿里云oss配置
endpoint: 
accessKeyId: 
accessKeySecret: 
bucketName: 
aliyunBaseUrl: 