server:
  id: 1  #所有calloutserver和toagentserver需修改为不一样的，取值范围1至1023
  port: 18024
  tomcat:
    max-threads: 800
    max-connections: 20000
spring:
  application:
    name: guiyu-callCenter-calloutserver
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 192.168.1.57 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码（默认为空）
    timeout: 5000 # 连接超时时间（毫秒）
    pool:
      max-active: 400 # 连接池最大连接数（使用负值表示没有限制
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 300 # 连接池中的最大空闲连接
      min-idle: 100 # 连接池中的最小空闲连接
  rabbitmq:
    host: 192.168.1.57
    port: 5672
    virtual-host: /
    username: guiyu
    password: 123456
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.5

endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
jdbc_driver0: com.mysql.jdbc.Driver
jdbc_url0: jdbc:mysql://192.168.1.57:3306/guiyu_callcenter?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
jdbc_username0: callcenter
jdbc_password0: callcenter@1234
validationQuery: SELECT 1
#数据库连接配置
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
jdbc:
  type: mysql

#注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
#        defaultZone: http://192.168.1.57:18001/eureka/
        defaultZone: http://guiyu-cloud-registeration:18001/eureka/
properties:
  error: error.properties

fsbot:
  homeDir: /Users/toolwiz.com/freeswitch/fsbot
  recordingsDir: ${fsbot.homeDir}/recordings/
  machineCode: SHANGHAI-000001
  allowDisturbed: true
  maxMediaTimeout: 8
  workStartTime: 08:30
  workEndTime: 21:00
  callMaxCountPerDay: 3
aliasr:
  accessId: 7mvC7CqfaKDWwfpN
  accessSecret: tBBA0vyrBc7zfLSsQpBNTSMh3qa6tA LTAInHHRM9fM0PHK aleg 800 null
ai:
  url: http://47.98.109.96:%s
  startPort: 15055
  portCount: 3
  wavFileHome: /home/aiwav/
  realWavFileHome: ${fsbot.homeDir}/home/aiwav/
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
#支持的最大拨打数量
callCount.max: 400
#是否开启挂机频率检测
callInspect.open: true
#录音补偿机制，检查多少天内的数据
callFileCheck.day.ago: 3
#xxl-job admin中心配置
xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://192.168.1.57:18016/xxl-job-admin
    executor:
      ip: 192.168.1.57
      port: 9024
      logpath: /home/logs/guiyu-callCenter-calloutserver-web
      logretentiondays: -1
    accessToken:
weixin:
  appid: wx017a03051262ec17  #跳转到的小程序appid
  templateId: sWm0PZIGJ0EZZ0gH3n7eeT__sC1mGxqqzhHkGXwzy_s  #模板id
  pagePath:
    callReordUrl: pages/detail/detail?id= #小程序通话详情页面
    reordListUrl: pages/list/list #小程序通话记录列表页面
rabbit:
  general:
    direct:
      queue: callCenter.record_update_mq #队列名称