server:
  port: 18006
  threadCount: 30
spring:
  application:
    name: guiyu-callcenter-fsagent
  rabbitmq:
    host: 192.168.1.81
    port: 5672
    virtual-host: /
    username: guiyu
    password: 123456
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.5

endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
#注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://guiyu-cloud-registeration:18001/eureka/

fs:
   #homeDir: /home/freeswitch/fs1
   homeDir: C:/Program Files/FreeSWITCH
   role: line_sim
   internalUse: true

#job:
#  clearRecord: 0 0 0 * * ?
#xxl-job admin中心配置
xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://192.168.1.78:18016/xxl-job-admin
    executor:
      ip: 192.168.1.78
      port: 9024
      logpath: /home/logs/guiyu-callCenter-fsagent-web
      logretentiondays: -1
    accessToken:

path:
    recordPath: D:/record/
    tempPath: /home/botstence_tmpl/
    ttsPath: /home/botstence_tmpl/tts/
    tempRecordPath: /home/aiwav

properties:
    error: properties/error.properties

rabbit:
  general:
    fanout:
      exchange: fanoutLineNoticeBindExchange
    direct:
      queue: callCenter.record_update_mq


