package com.guiji.dispatch.dao;

import com.guiji.dispatch.dao.entity.Plan;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_plan
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_plan
     *
     * @mbggenerated
     */
    int insert(List<Plan> record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_plan
     *
     * @mbggenerated
     */
    Plan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_plan
     *
     * @mbggenerated
     */
    List<Plan> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_plan
     *
     * @mbggenerated
     */
    List<Plan> selectByUserId(@Param("userId") Integer userId, @Param("taskNum") Integer taskNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dispatch_plan
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(List<Plan> record);
}