server:
  port: 18013
spring:
  application:
    name: guiyu-datadic
  datasource:
    url: jdbc:mysql://192.168.1.81:3306/guiyu_base?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&allowMultiQueries=true
    username: base
    password: base@1234
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 2
    host: 192.168.1.81
    password: 123456
    port: 6379
    pool:
      max-active: 400
      max-wait: -1
      min-idle: 100
      max-idle: 300
  rabbitmq:
    host: 192.168.1.81
    port: 5672
    virtual-host: /
    username: guiyu
    password: 123456
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.5

endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false

 #数据库连接配置
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
jdbc:
  type: mysql
#注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://guiyu-cloud-registeration:18001/eureka/
    instance:
      status-page-url: http://localhost:18000/eureka//swagger-ui.html
#网关地址
gateway:
  host: http://guiyu-cloud-zuul:18000/
properties:
  error: properties/error.properties