server:
  port: 18011
#myconfig
spring:
  application:
    name: guiyu-auth-web  
  datasource:  
    type: com.alibaba.druid.pool.DruidDataSource  
    url: jdbc:mysql://192.168.1.81:3306/guiyu_base?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&verifyServerCertificate=false&allowMultiQueries=true
    username: root
    password: Root@123456
    driver-class-name: com.mysql.jdbc.Driver  
    minIdle: 5
    maxActive: 200
    initialSize: 5
    timeBetweenEvictionRunsMillis: 3000  
    minEvictableIdleTimeMillis: 300000  
    validationQuery: SELECT 'ZTM' FROM DUAL  
    testWhileIdle: true  
    testOnBorrow: false  
    testOnReturn: false
  redis:
    database: 0
    host: 192.168.1.81
    password: 123456
    port: 6379  
    pool:
      max-active: 400
      max-wait: -1
      min-idle: 100
      max-idle: 300
  cache:
    type: redis
    cache-names: shiro.session,shiro.time 
  rabbitmq:
    host: 192.168.1.81
    port: 5672
    virtual-host: /
    username: guiyu
    password: 123456
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.5

endpoints:
  health:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
mybatis:   
  mapperLocations: classpath*:mappers/**/*.xml
  config-location: classpath:config/mybatis-config.xml      
  
properties:
  error: properties/error.properties
#注册中心配置      
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://guiyu-cloud-registeration:18001/eureka/
      instance:
          status-page-url: http://localhost:18000/eureka//swagger-ui.html
##网关地址
gateway:
   host: http://guiyu-cloud-zuul:18000/

ribbon:
  ReadTimeout: 30000 #请求处理的超时时间
  ConnectTimeout: 30000  #请求连接的超时时间
  MaxAutoRetries: 0   #对当前实例的重试次数
  MaxAutoRetriesNextServer: 1  #切换实例的重试次数
  eureka:
    enabled: true
weixin:
  appid: wx1558a28a6907c3e8  #跳转到的小程序appid
  templateId: sWm0PZIGJ0EZZ0gH3n7eeT__sC1mGxqqzhHkGXwzy_s  #模板id

      
rabbit: 
  general: 
    direct: 
      queue: SyncAgentMembers.direct.Auth|DelAgentMembers.direct.Auth
    fanout: 
      exchange: AddOrgNotice.fanoutExchange.Auth
      queue: AddOrgNotice.fanout.Dispatch,AddOrgNotice.fanout.CallCenter


    